name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run tests
              run: npm test
            - name: Build and push the image
              run: |
                docker login --username kparekh21 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/kparekh21/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/kparekh21/arithmetic-service:latest 
            - name: Build and push the image to azure
              run: |
                docker login --username practicum16 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum16.azurecr.io
                docker tag ghcr.io/kparekh21/arithmetic-service:latest practicum16.azurecr.io/arithmetic-service:latest
                docker push practicum16.azurecr.io/arithmetic-service:latest


